[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200


[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${Mqd-8wRM1LELtnwAYgKXY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${}"

[etherscan]
mainnet = { key = "${KBCGGGP1547B4DCDIDB5UB6R92NE1XKW7H}" }
sepolia = { key = "${KBCGGGP1547B4DCDIDB5UB6R92NE1XKW7H}" }